Adjustments to libged-static + plugin system build logic
We had the shared library target for libged using the correct CMake
mechanisms for collecting plugin sources and definitions, but not the
static version.  We were still building a static version, but it was
missing most of the actual logic - got a report from Daniel Rossberg
that trying to link to libged.a resulted in many failures such as:

/bin/ld: libbrlcad.so: undefined reference to `__ged_cmd_ptr_fbclear_cmd'

Also observed the static library for libged was much smaller than the
shared, which suggested missing logic.  Was able to confirm locally -
libged.a was 17M vs. 33M for the shared version.With the above fixes the
libged.a static size is now 81M.