gcc v13.0.1 doesn't like the std::move here
Error: moving a temporary object prevents copy elision [-Werror=pessimizing-move]
note: remove ‘std::move’ call
(cherry picked from commit b848c7fd6dbc1fa869d20a5031a3ee49edad4633)