Another new GCC error - dangling-reference
error: possibly dangling reference to a temporary [-Werror=dangling-reference]
(cherry picked from commit f39d68704d1febee6165510a2817668988b74533)