revision 74695 causes error C2668 (ambigous call to overload function) in src\libged\facetize.cpp lines 395 and 398 with MSVS 2019 => moved "#define open _open" back to its place before this revision - will have to see if it causes an issue with MSVS version 2017
svn:revision:74968
svn:branch:trunk
svn:account:d_rossberg